name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on code push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub using API Token
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # Step 3: Build and Push Docker Image with 'latest' Tag
    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/frontend-app:latest
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME
      env:
        IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest

    # Step 4: Trigger Argo CD Sync
    - name: Trigger Argo CD Sync
      run: |
        curl -k -X POST -H "Content-Type: application/json" \
          -H "Authorization: Bearer $ARGOCD_AUTH_TOKEN" \
          -d '{"repoURL":"https://github.com/kandaj/frontend"}' \
          $ARGOCD_SERVER/api/v1/applications/frontend-app/sync
      env:
        ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
        ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}